Browser=Chrome
Browser.Version=148.0.7778.97
OS=Windows-10
OS.Version=10.0.26200-SP0
Python.Version=3.10.11
Pytest.Version=8.1.1
Test.Environment=QA
Test.Application=Notes-Automation
Base.URL=https://practice.expandtesting.com/notes/app
API.Base.URL=https://practice.expandtesting.com/notes/api
Test.Date=${allure.environment.date}
