name: selenium-grid

services:

  selenium-hub:

    image: selenium/hub:4.21.0
    container_name: selenium-hub

    restart: always

    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

    environment:
      SE_SESSION_REQUEST_TIMEOUT: 600

    networks:
      - selenium-grid



  chrome-node-1:

    image: selenium/node-chrome:4.21.0
    container_name: chrome-node-1

    restart: always

    depends_on:
      - selenium-hub

    shm_size: 2gb

    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 1
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_SESSION_TIMEOUT: 300
      SE_JAVA_OPTS: "-Xmx512m"

    ports:
      - "7900:7900"

    networks:
      - selenium-grid



  chrome-node-2:

    image: selenium/node-chrome:4.21.0
    container_name: chrome-node-2

    restart: always

    depends_on:
      - selenium-hub

    shm_size: 2gb

    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 1
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_SESSION_TIMEOUT: 300
      SE_JAVA_OPTS: "-Xmx512m"

    ports:
      - "7901:7900"

    networks:
      - selenium-grid


networks:
  selenium-grid: