[pytest]

markers =
    ui: UI tests using Selenium WebDriver
    api: API tests using requests library
    e2e: End-to-end tests combining UI and API

addopts =
    --alluredir=reports/allure-results
    -v
    --strict-markers
    ; --capture=no
    --tb=short

log_cli = false

# Allure configuration
allure_report_dir = reports/allure-results