FROM jenkins/jenkins:lts

USER root

# ---------------------------------------------------
# System Update
# ---------------------------------------------------

RUN apt-get update

# ---------------------------------------------------
# Install Core Utilities
# ---------------------------------------------------

RUN apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    git \
    curl \
    unzip \
    wget \
    docker.io \
    docker-compose \
    default-jre

# ---------------------------------------------------
# Install Allure
# ---------------------------------------------------

RUN wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip && \
    unzip allure-2.29.0.zip && \
    mv allure-2.29.0 /opt/allure && \
    ln -s /opt/allure/bin/allure /usr/bin/allure

# ---------------------------------------------------
# Verify Installations
# ---------------------------------------------------

RUN python3 --version && \
    pip3 --version && \
    docker --version && \
    docker-compose --version && \
    allure --version

# ---------------------------------------------------
# Jenkins User Permissions
# ---------------------------------------------------

RUN usermod -aG docker jenkins

USER root